//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemKeskin.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseCemKeskinEntities : DbContext
    {
        public DatabaseCemKeskinEntities()
            : base("name=DatabaseCemKeskinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAboutMe> TBLAboutMe { get; set; }
        public virtual DbSet<TBLLogin> TBLLogin { get; set; }
        public virtual DbSet<TBLReferences> TBLReferences { get; set; }
        public virtual DbSet<TBLServices> TBLServices { get; set; }
        public virtual DbSet<TBLSocialMedia> TBLSocialMedia { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLEducation> TBLEducation { get; set; }
        public virtual DbSet<TBLExperiences> TBLExperiences { get; set; }
        public virtual DbSet<TBLResume> TBLResume { get; set; }
    }
}
