//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemKeskin.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLServices
    {
        public int Id { get; set; }
        public string ServicesTitle { get; set; }
        public string ServicesContent { get; set; }
        public string ServicesIcon { get; set; }
    }
}
